version: 2.1

workflows:
  version: 2
  test_build:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo pip3 install docker-compose
      - setup_remote_docker
      - run:
          name: Build with docker-compose
          command: |
            docker-compose build
      